baseURL = 'https://xingxi94.top/'
title = 'xingxi的博客'
theme = "github.com/D-Sketon/hugo-theme-reimu"

defaultContentLanguage = 'zh-CN'

[languages.zh-CN]
languageName = '简体中文'
weight = 1
languageCode = 'zh-CN'
hasCJKLanguage = true

[languages.en]
languageName = 'English'
weight = 2
languageCode = 'en'
contentDir = 'content/en/posts'
title = "Xingxi's Blog"