baseURL = 'https://xingxi94.top/'
title = 'xingxi的博客'
theme = "reimu"
languageCode = 'zh-CN'
defaultContentLanguage = 'zh-CN'
[languages]
[languages.zh-CN]
languageName = '简体中文'
weight = 1
[languages.en-US]
languageName = "English"
weight = 2
hasCJKLanguage = true
[markup.highlight]
guessSyntax = true
noClasses = false
[caches]
  [caches.images]
    dir = ':cacheDir/images'