baseURL = 'https://xingxi94.top/'
title = 'xingxi的博客'
theme = "reimu"
languageCode = 'zh-CN'
defaultContentLanguage = 'zh-CN'
[languages]
[languages.zh-CN]
languageName = '简体中文'
weight = 1
languageCode = 'zh-CN'
hasCJKLanguage = true